# Generated by Django 5.2.8 on 2025-11-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('actividad', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
