# Generated by Django 5.2.8 on 2025-12-05 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadRegistrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['actividad'],
            },
        ),
        migrations.CreateModel(
            name='Cilindro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_grabado', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado_actual', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ETIQUETADO', 'Etiquetado'), ('TRAZADO', 'Trazado'), ('EN_PULIDOR', 'En Pulidor'), ('EN_PINTOR', 'En Pintor')], default='RECIBIDO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_general', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Guardar como día 1 del mes')),
                ('total_mes', models.PositiveIntegerField(default=0, editable=False)),
                ('variacion_porcentual', models.FloatField(default=0, editable=False)),
                ('actividad_destacada', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('TRAZADO', 'Trazado'), ('ETIQUETADO', 'Etiquetado'), ('NIT_CREADO', 'NIT Creado')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.AddField(
            model_name='cilindro',
            name='nit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reportes.nit'),
        ),
        migrations.AddField(
            model_name='actividadregistrada',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='reportes.reportediario'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='cilindro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazas', to='reportes.cilindro'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
